# Generated by Django 5.2.8 on 2026-04-01 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_problem_options_alter_solution_options_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-created_at'], 'permissions': (('view_reports_dashboard', 'Can view reports dashboard'),)},
        ),
        migrations.AddField(
            model_name='problem',
            name='accepted_solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for_problems', to='main.solution'),
        ),
    ]
