# Generated by Django 5.2.8 on 2025-12-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_problem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
