# Generated by Django 5.2.8 on 2026-04-01 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_problem_options_problem_accepted_solution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='main.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_presences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'created_at'],
            },
        ),
    ]
