# Generated by Django 5.2.8 on 2026-02-01 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_problem_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.problem'),
        ),
        migrations.AddField(
            model_name='solution',
            name='answer_type',
            field=models.CharField(choices=[('direct', 'Direct Answer'), ('explanation', 'Conceptual Explanation'), ('opinion', 'Opinion / Discussion'), ('example', 'Worked Example')], default='direct', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.solution'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('solution', 'user')},
        ),
    ]
