# Generated by Django 5.2.8 on 2026-02-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aiconversation_aimessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimessage',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='AIConversation',
        ),
        migrations.DeleteModel(
            name='AIMessage',
        ),
    ]
