# Generated by Django 5.2.8 on 2026-04-01 23:04

from django.db import migrations


def delete_legacy_ai_solution_rows(apps, schema_editor):
    Solution = apps.get_model("main", "Solution")
    Solution.objects.filter(ai_generated=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_emaillog'),
    ]

    operations = [
        migrations.RunPython(delete_legacy_ai_solution_rows, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='solution',
            name='ai_generated',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='message',
        ),
    ]
